vim.g.mapleader = ' '

require('plugins')
require('config.completion')
--require('config.copilot')
require('config.fzf')
require('config.gitsigns')
require('config.go')
require('config.lsp')
require('config.lualine')
require('config.mason')
require('config.neotree')
require('config.surround')
require('config.treesitter')
require('settings')
