vim.opt.autoindent = true
vim.opt.background = 'dark'
vim.opt.completeopt = {'menu', 'menuone', 'noselect'}
vim.opt.diffopt = { 'filler', 'iwhite' }
vim.opt.enc = 'utf-8'
vim.opt.expandtab = true
vim.opt.fileencoding = 'utf-8'
vim.opt.foldmethod='expr'
vim.opt.foldexpr="nvim_treesitter#foldexpr()"
vim.opt.foldenable=false
vim.opt.hidden = true
vim.opt.history = 50
vim.opt.ignorecase = true
vim.opt.incsearch = true
vim.opt.laststatus = 2
vim.opt.linebreak = true
vim.opt.number = true
vim.opt.relativenumber = true
vim.opt.ruler = true
vim.opt.scrolloff = 1
vim.opt.showcmd = true
vim.opt.showmatch = true
vim.opt.smartcase = true
vim.opt.shiftwidth = 2
vim.opt.softtabstop = 2
vim.opt.termguicolors = true
vim.opt.timeoutlen = 10000
vim.opt.ttimeoutlen = 10000
vim.opt.virtualedit = 'block'
vim.opt.wildmenu = true
vim.opt.wildmode = {'list', 'full'}
vim.opt.mouse = ''
